#!/bin/bash -u
# Script_name     : checkpower
# Author          : Bert Lindeman
# Description     : Check the battery voltage and warn if the voltage is 
#                   less than 7 volts,
#                   also set the left EV3 led to blinking green, amber or red.
# Version         : v1.2
# Date            : 2014-08-26
# Usage           : checkpower 
#                   No arguments needed nor used
# Notes           : ! TOBE verified: At what voltage does the brick shutdown.
#                     assumed 6 volts would be acceptable.
#                   o power (using an EV3 rechargable battery) usualy drops 0.1 V
#                     in about half an hour. So IF this script is run as cron task
#                     running it each 10 minutes should be sufficient.
# Copyright       : 2014 Bert Lindeman
# License         : GPL-3.0+
#
#============================================================================
#
# Changelog       :
# Date     By       Description
# 20140826 BL       o Add header
#                   o Do not ALWAYS state that power is "OK"
#                     but show the status WARN / MED / LOW / OK
#                   o whole algorithm did NOT work :-(
#                   o Check if ENVIRONMENT variable is set.
# 20140827 BL       o 6 volts is just a bit too low as last warning level
#                     Last drop of voltage e.g. was too much
#                     from 6303066 to 5668733 in 10 minutes (my check interval)
#                     Causing auto? shutdown.
# 20140902 BL       o add the momentary current to the message
# 20140914 BL       o add the voltage to the blinkvoltage call,
#                     to adapt the type of blinking.
#                     Since kernel 3.16.1 leds can be better controlled.
#============================================================================


   status=UNKWN  # set default
   
   cd /sys/devices/platform/legoev3-battery/power_supply/legoev3-battery
   voltage=`cat voltage_now`
   # voltage is in microvolt as documented in include/linux/power_supply.h
   # Did not take the trouble to format this.
   current=`cat current_now`
   
   if   [ $voltage -lt 6200000 ]; then 
        /usr/local/bin/blinkvoltage red $voltage
        beep
        status=LOW
        # issue a warning; if setup, then cron can email messages like this.
        echo -e "WARNING: voltage $status: $voltage"
   elif [ $voltage -lt 6500000 ]; then 
        /usr/local/bin/blinkvoltage amber $voltage 
        status=MED
        echo -e "WARNING: voltage $status: $voltage"
   elif [ $voltage -lt 7000000 ]; then 
        /usr/local/bin/blinkvoltage green $voltage
        status=WARN  
   else
        /usr/local/bin/blinkvoltage none $voltage
        status=OK
   fi  

   # Assign "non-cron" if ENVIRONMENT is unset or null, and thus prevent error "variable unbound":
   : "${ENVIRONMENT:=non-cron}"
   
   if [ "$ENVIRONMENT" == "non-cron" ]; then # just a message; no need to add to syslog 
      echo -e "voltage $status: $voltage; current: $current "
   else
      echo -e "`date +"%b %d %T"` $HOSTNAME cron: $ENVIRONMENT -  voltage $status: $voltage; current: $current" >> /var/log/syslog
   fi   
