#!/bin/bash -u           
# Script_name     : showactivity
# Author          : Bert Lindeman
# Description     : Let the rightside green EV3-led blink depending on I/O activiy
# Version         : v1.3
# Date            : 2014-11-04
# Usage           : showactivity
# Notes           : No parameters used nor checked
# Copyright       : 2014 Bert Lindeman
# License         : GPL-3.0+
#
#============================================================================
#
# Changelog        
# Date     By       Description
# 20141104 BL       prepare for release v1.3
# 20140826 BL       o Add script header
#                   o No longer show triggers of the leds (confusing)
#
#============================================================================


# These were available on Wheezy
# No longer available on Jessie
#echo phy0tx    > /sys/class/leds/ev3\:green\:right/trigger
#echo phy0rx    > /sys/class/leds/ev3\:green\:left/trigger
#echo phy0assoc > /sys/class/leds/ev3\:red\:left/trigger
#echo phy0radio > /sys/class/leds/ev3\:red\:right/trigger
#
# set right green led to show I/O activity: 
echo mmc0  > /sys/class/leds/ev3\:green\:right/trigger
echo 1     > /sys/class/leds/ev3\:green\:right/brightness
#
#echo heartbeat  > /sys/class/leds/ev3\:red\:right/trigger
#echo 117        > /sys/class/leds/ev3\:red\:right/brightness
#
