#!/bin/bash -u           
# Script_name     : showsensors
# Author          : Bert Lindeman
# Description     : Show info of recognized sensors
# Version         : v1.1
# Date            : 2014-08-26
# Usage           : ./showsensors
# Notes           : 
# Copyright       : 2014 Bert Lindeman
# License         : GPL-3.0+
#
#============================================================================
#
# Changelog        
# Date     By       Description
#
#
#============================================================================


#
# determine which interface services what input port:
#
IFS=$' \n' read -a sensors <<< "`echo /sys/class/msensor/sensor*/`"
#
for  i in "${!sensors[@]}" # ! walk the indexes
do
  # echo -e "Process $i \"${sensors[$i]}\""
  if [ -e "${sensors[$i]}" ]; then
      cd "${sensors[$i]}"
      echo "Process $i `pwd`" 
      echo " sensor $i type: `cat type_id` on port `cat port_name` "
      echo "dp :                  `cat dp`"
      echo "mode:                 `cat mode`"
      echo "modes:                `cat modes`"
      echo "num_values:           `cat num_values`"
      num_values="`cat num_values`"
      for (( v=0; v<$num_values; v++ ))
      do
        echo "value$v:               `cat value$v`"
      done
      echo "units:                `cat units`"
      echo -e "uevent:          \n`cat uevent` \n"
      echo " "
  else
      echo -e "Expected path \"${sensors[$i]}\" does not exist"
  fi
done     
