#!/bin/bash -u           
# Script_name     : showmotor
# Author          : Bert Lindeman
# Description     : Show status of connected motors
# Version         : v1.1
# Date            : 2014-08-26
# Usage           : showmotor
# Notes           : Only tested with LEGO EV3 and NXT motors
# Copyright       : 2014 Bert Lindeman
# License         : GPL-3.0+
#
#============================================================================
#
# Changelog        
# Date     By       Description
# 20140826 BL       Add script header
#
#============================================================================



# show motor status
. /usr/local/bin/asciicolors
#
# determine which motor(port) is connected to what tacho-motor-number  
#   /sys/class/tacho-motor/tacho-motor*/port_name is the link between motor# and port
#
IFS=$' \n' read -a tachoPath <<< "`echo /sys/class/tacho-motor/tacho-motor*/`"
#
for  i in ${!tachoPath[@]} # ! walk the indexes
do
  #echo -e "process $i ${tachoPath[$i]}"
 if [ -e ${tachoPath[$i]} ]; then
   cd ${tachoPath[$i]}  
   #
   if [ $? -eq 0 ] ;  then
     printf "${brblue}Motor on port $brwhite%s$brblue as type=$brwhite%-10s$brblue at\
 $brwhite%s$white\n" "`cat port_name`" "`cat type`" "${tachoPath[$i]} "

     curval=`cat duty_cycle_sp`
     line1_1=`printf "%-21s %12d\n"  "duty_cycle_sp:"        "$curval"`

     curval=`cat pulses_per_second_sp`
     line2_1=`printf "%-21s %12d\n"  "pulses_per_second_sp:" "$curval"`
     line3_1="_ ."     

     curval=`cat position_sp`
     line4_1=`printf "%-21s %12d\n"  "position_sp:"          "$curval"`

     curval=`cat time_sp`
     line5_1=`printf "%-21s %12d\n"  "time_sp:"              "$curval"`

     curval=`cat ramp_down_sp`
     line6_1=`printf "%-21s %12d\n"  "ramp_down_sp:"         "$curval"`

     curval=`cat ramp_up_sp`
     line7_1=`printf "%-21s %12d\n"  "ramp_up_sp:"           "$curval"`
     line8_1="_ ."          
     line9_1="_ ."          
     line10_1="  "          
     
     curval=`cat duty_cycle`
     line1_2=`printf "%-21s %12d\n"  "duty_cycle:"           "$curval"`

     curval=`cat pulses_per_second`
     line2_2=`printf "%-21s %12d\n"  "pulses_per_second:"    "$curval"`
     
     curval=`cat polarity_mode`
     line3_2=`printf "%-21s %12s\n"  "polarity_mode:"        "$curval"`
     
     curval=`cat position`
     line4_2=`printf "%-21s %12d\n"  "position:"             "$curval"`

     curval=`cat position_mode`
     line5_2=`printf "%-21s %-50s\n" "position_mode:"        "$curval"`

     curval=`cat regulation_mode`
     line6_2=`printf "%-21s %12s\n"  "regulation_mode:"      "$curval"`

     curval=`cat run_mode`
     line7_2=`printf "%-21s %12s\n"  "run_mode:"             "$curval"`

     curval=`cat state`
     line8_2=`printf "%-21s %s\n"    "state:"                "$curval"`

     curval=`cat stop_mode`
     line9_2=`printf "%-21s %12s\n"  "stop_mode:"            "$curval"`
     line10_2="_ ."     
     
     curval=`cat run`
     line1_3=`printf "%-21s %8d\n"   "run:"                  "$curval"`

     curval=`cat estop`
     line2_3=`printf "%-21s %8d\n"   "estop:"                "$curval"`

     curval=`cat speed_regulation_D`
     line3_3=`printf "%-21s %8d\n"   "speed_regulation_D:"   "$curval"`

     curval=`cat speed_regulation_I`
     line4_3=`printf "%-21s %8d\n"   "speed_regulation_I:"   "$curval"`

     curval=`cat speed_regulation_K`
     line5_3=`printf "%-21s %8d\n"   "speed_regulation_K:"   "$curval"`

     curval=`cat speed_regulation_P`
     line6_3=`printf "%-21s %8d\n"   "speed_regulation_P:"   "$curval"`
     # type  already in top of the display
     curval=`cat uevent`
     line7_3=`printf "%-20s %s\n"    "uevent:" "$curval"`
     
     line8_3="_ ."
     line9_3="_ ."     
     tabc=$brblue
     # Long string....
     curval=`cat stop_modes`
     line10_1=`printf "$tabc%-21s $white%s\n"   "stop_modes:"       "$curval"`
     echo " "
     printf "$brwhite%32s %32s %32s$white\n" "  == setpoints ==  " "  == state     ==  " "  == switches  ==" 
     runval=`cat run`
     if [ "$runval" == 0 ] ; then runcol=${yellow}
                             else runcol=${brgreen} 
     fi
     printf "$tabc%-21s $white%8s $brwhite|$white $tabc%-18s $white%11s $brwhite|$white $tabc%-21s $runcol%10s\n"  $line1_1 $line1_2 $line1_3
     printf "$tabc%-21s $white%8s $brwhite|$white $tabc%-18s $white%11s $brwhite|$white $tabc%-21s $white%10s\n"  $line2_1 $line2_2 $line2_3
     printf "$tabc%-21s %8s $brwhite|$white $tabc%-18s $white%11s $brwhite|$white $tabc%-21s $white%10s\n"  $line3_1 $line3_2 $line3_3 
     printf "$tabc%-21s $white%8s $brwhite|$white $tabc%-18s $white%11s $brwhite|$white $tabc%-21s $white%10s\n"  $line4_1 $line4_2 $line4_3 
     printf "$tabc%-21s $white%8s $brwhite|$white $tabc%-18s $white%11s $brwhite|$white $tabc%-21s $white%10s\n"  $line5_1 $line5_2 $line5_3 
     printf "$tabc%-21s $white%8s $brwhite|$white $tabc%-18s $white%11s $brwhite|$white $tabc%-21s $white%10s\n"  $line6_1 $line6_2 $line6_3 
     printf "$tabc%-21s $white%8s $brwhite|$white $tabc%-18s $white%11s $brwhite|$white $tabc%-21s $white%10s\n"  $line7_1 $line7_2 $line7_3 
     printf "$tabc%-21s %8s $brwhite|$white $tabc%-18s $runcol%11s $brwhite|$white $tabc%-21s %10s\n"  $line8_1 $line8_2 $line8_3 
     printf "$tabc%-21s %8s $brwhite|$white $tabc%-18s $white%11s $brwhite|$white $tabc%-21s %10s\n"  $line9_1 $line9_2 $line9_3 
     #
     echo -e $line10_1 # 10_2 and 10_3 not used. 
     echo ""

  else
    echo "does not exist entry $i  ${tachoPath[$i]}  " 
  fi 
 fi 
done
