#!/bin/bash -u           
# Script_name     : showactivity
# Author          : Bert Lindeman
# Description     : Let the rightside green EV3-led blink depending on I/O activiy
# Version         : v1.3
# Date            : 2014-11-04
# Usage           : showactivity
# Notes           : No parameters used nor checked
# Copyright       : 2014 Bert Lindeman
# License         : GPL-3.0+
#
#============================================================================
#
# Changelog        
# Date     By       Description
# 20141104 BL       prepare for release v1.3
# 20140826 BL       o Add script header
#                   o No longer show triggers of the leds (confusing)
# 20141202 BL       Set mmc0 trigger to outA for PF-leds
# 20150114 BL       adapt for kernel 3.16.7-ckt3-ev3dev1
# 20150116 BL       use /usr/local/bin/tryPF to add leds on outA
#============================================================================
#
# set right green led to show I/O activity: 
echo mmc0  > /sys/class/leds/ev3\:green\:right/trigger
sleep 0.25s
echo 1     > /sys/class/leds/ev3\:green\:right/brightness
sleep 0.25s
#
#
. /usr/local/bin/bert_ev3dev_functions


portletter="A"
port="out${portletter}"
# verify there is NO MOTOR on port outA
  findmotorctl "${port}"
   if listcontains "${SEENPORT}" "outA" ; then
    echo "Motor present on ${port}: no action"
    exit
  else
    if [ "${CURMOTOR}" == "???????" ]; then
      echo "OK, no motor on ${port}: is outA already \"led\"?"
      if [ ! -e /sys/class/leds/ev3\:\:outA/trigger ]; then
        echo "Field trigger on outA does not exist yet: Add PF led on port outA"
        /usr/local/bin/tryPF outA led   
      fi 
    fi
  fi

if [ -w /sys/class/leds/ev3\:\:outA/trigger ]; then
  echo "set \"/sys/class/leds/ev3\:\:outA/trigger\" to \"mmc0\" "
  echo mmc0 > /sys/class/leds/ev3\:\:outA/trigger
fi