#!/bin/bash -u           
# Script_name     : showsound
# Author          : Bert Lindeman
# Description     : Show info about EV3 sound
# Version         : v1.1
# Date            : 2014-08-26
# Usage           : showsound
# Notes           : o No parameters used
#                   o Do not confuse with sound-SENSOR
# Copyright       : 2014 Bert Lindeman
# License         : GPL-3.0+
#
#============================================================================
#
# Changelog        
# Date     By       Description
# 20140826 BL       Add script header
# 20140907 BL       Use centralized functions
#============================================================================


. /usr/local/bin/bert_ev3dev_functions

  cd "/sys/devices/platform/snd-legoev3/"
  echo "Report from `pwd`"

  printf  "${brblue}modalias: ${green} %-26s${white}\n" "`cat modalias`"
  printf  "${brblue}tone    : ${green} %-26s${white}\n" "`cat tone`"
  printf  "${brblue}volume  : ${green} %-26s${white}\n" "`cat volume`"
  printf  "${brblue}uevent  :\n ${green} %-26s${white}\n" "`cat uevent`"
  echo -e "${endColor} " # back to normal
