#!/bin/bash -u           
# Script_name     : showsound
# Author          : Bert Lindeman
# Description     : Show info about EV3 sound
# Version         : v1.1
# Date            : 2014-08-26
# Usage           : showsound
# Notes           : o No parameters used
#                   o Do not confuse with sound-SENSOR
# Copyright       : 2014 Bert Lindeman
# License         : GPL-3.0+
#
#============================================================================
#
# Changelog        
# Date     By       Description
# 20140826 BL       Add script header
#
#============================================================================


  if [ -e /usr/local/bin/asciicolors ]; 
  then .  /usr/local/bin/asciicolors
  else    black='\e[0;30m'
    red='\e[0;31m'
    green='\e[0;32m'
    yellow='\e[0;33m'
    blue='\e[0;34m'
    magenta='\e[0;35m'
    cyan='\e[0;36m'
    white='\e[0;37m'

    brblack='\e[1;30m'
    brred='\e[1;31m'
    brgreen='\e[1;32m'
    bryellow='\e[1;33m'
    brblue='\e[1;34m'
    brmagenta='\e[1;35m'
    brcyan='\e[1;36m'
    brwhite='\e[1;37m'

    endColor='\e[0m'
  fi

  cd "/sys/devices/platform/snd-legoev3/"
  echo "Report from `pwd`"

  printf  "${brblue}modalias: ${green} %-26s${white}\n" "`cat modalias`"
  printf  "${brblue}tone    : ${green} %-26s${white}\n" "`cat tone`"
  printf  "${brblue}volume  : ${green} %-26s${white}\n" "`cat volume`"
  printf  "${brblue}uevent  :\n ${green} %-26s${white}\n" "`cat uevent`"
  echo -e "${endColor} " # back to normal
