#!/bin/bash -ue           
# Script_name     : stopmotors
# Author          : Bert Lindeman
# Description     : Stop all recognized tacho motors
# Version         : v1.2
# Date            : 2014-08-26
# Usage           : stopmotors
# Notes           : 
# Copyright       : 2014 Bert Lindeman
# License         : GPL-3.0+
#
#============================================================================
#
# Changelog        
# Date     By       Description
# 20140907 BL       Use centralized functions
# 20140916 BL       Do not use fixed number suffix on tacho-motor#
# 20141022 BL       Add rxc-motor and rxc-led
#                   Adapt to "force motor driver"
# 20141024 BL       Temporary "fix" for issue 186 (duty-cycle only if "run")
#============================================================================


. /usr/local/bin/bert_ev3dev_functions

#
showmotor () {
      runfilename=${1:-run}
      if [ $motorpower -eq 0 ]; then motorcolor=$brgreen
                                else motorcolor=$brred
      fi
      printf  "${motorcolor}%3s$brwhite" "`cat ${MOTORPATH}/$runfilename`"
}

#
# "old" directory name before kernel 3.16.1-6:
for m in /sys/class/tacho-motor/tacho-motor*
  do
    MOTORPATH="$m"
    if [ -e $MOTORPATH ]; then
      printf "%-40s %-6s " "$MOTORPATH/run" "status" 
      
      # report status before reset
      motorpower=`cat $MOTORPATH/run`
      printf "$brblue %-6s $brwhite%3s " "before" "`showmotor`" 

      # set back to zero:
      echo   0 > "$MOTORPATH/run"

      # report status after reset
      motorpower=`cat $MOTORPATH/run`
      printf "$brblue %-6s $brwhite%-3s\n" "after" "`showmotor`"
    fi
  done
#  
# "new" directory name starting at kernel 3.16.1-6:
for m in /sys/class/tacho-motor/motor*
  do
    MOTORPATH="$m"
    if [ -e $MOTORPATH ]; then
      printf "%-40s %-6s " "$MOTORPATH/run" "status" 
      
      # report status before reset
      motorpower=`cat $MOTORPATH/run`
      printf "$brblue %-6s $brwhite%3s " "before" "`showmotor`" 

      # set back to zero:
      echo   0 > "$MOTORPATH/run"

      # report status after reset
      motorpower=`cat $MOTORPATH/run`
      printf "$brblue %-6s $brwhite%-3s\n" "after" "`showmotor`"
    fi
  done
  
  # ================================
           
  for m in /sys/class/dc-motor/motor*/
  do
    MOTORPATH="$m"
    if [ -e $MOTORPATH ]; then
      printf "%-40s %-6s " "${MOTORPATH}duty_cycle" "status" 
      # report status before reset
      motorpower=`cat ${MOTORPATH}duty_cycle`
      printf "$brblue %-6s $brwhite%3s " "before" "`showmotor duty_cycle`" 
#     echo "DEBUG Running in dir `pwd` MOTORPATH=${MOTORPATH}"
      #
      # echo duty_cycle only accepted if command=run: ISSUE 186
      #
      prevcommand=`cat ${MOTORPATH}command`
      echo "run" > ${MOTORPATH}command
      # set back to zero:
      echo 0 > "${MOTORPATH}duty_cycle"
      # set command back:
      echo $prevcommand > ${MOTORPATH}command

      # report status after reset
#     echo "DEBUG Running in dir `pwd` MOTORPATH=${MOTORPATH}"
      motorpower=`cat ${MOTORPATH}duty_cycle`
      printf "$brblue %-6s $brwhite%-3s\n" "after" "`showmotor duty_cycle`"
    fi      
    # controldir=`find /sys/class/${motordir} -name "motor*"`
  done
